name: CI Checks
run-name: Running Terraform Checks by ${{ github.actor }}

on:
  pull_request:
    branches:
      - main

jobs:
  initial-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Getting initiator name
        run: echo "Workflow initiated by ${{ github.actor }} from branch ${{ github.ref_name }}"

  terraform-checks:
    runs-on: ubuntu-latest
    needs: initial-checks
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

  snyk-checks:
    name: Basic Snyk checks
    runs-on: ubuntu-latest
    needs: initial-checks
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Code Scan And Check Snyk Scan Results
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: "--report --severity-threshold=high --scan=resource-changes"

      - name: Run Snyk Code Test Scan And Check Snyk Scan Results
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test

      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  summary:
    needs: [terraform-checks, snyk-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          TF_STATUS=${{ needs.terraform-checks.outputs.status }}
          SNYK_STATUS=${{ needs.snyk-checks.outputs.status }}

          echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| tf-check       | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo "| snyk-check     | $SNYK_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
